swagger: '2.0'
info:
  title: Intrinno API
  description: Intrinno API
  version: "1.0.0"
  # the domain of the service
host: intrinno.mx:9000
  # array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /app/spec-files
produces:
  - application/json
paths:
  /comments/index:
    post:
      summary: List Comments
      tags:
        - Comments
      parameters:
      
        - name: page
          in: body
          schema:
           type: integer
          description: The count starts from 0.
          required : true
          
        - name: commentsPerPage
          in: body
          schema: 
           type: integer
          description: "The comments that are going to be show per page"
          required: true
          
          
        - name: commentableId
          in: body
          schema:
           type: "string"
          description: "The _id of the document that is going to be commented"
          required: true
          
        - name: filter
          in: body
          schema: 
            filter: 
              desc: true/false
          description : "The options desc returns the list comments in descending order"
          required: false
          
      responses:
        200:
          description: List comments
          schema:
            status  : 200
            message : "List comments"
            data      :
              objects : 
                - _id   : "asdklajqwe123123"
                  text : "Text message"
                  files: 
                    _id: "asdas123d123"
                    name: "new_file.docx" 
                    url: "https://aws3.amazon.com/asldkjalsk123d.docx"
                  likeable: true/false
                  editable : true/false
                  likes : 15
                  reported: false
                  blocked: false
                  createdBy: {}
                  timestamps: 
                    createdAt : "random date"
                    updatedAt : "random date"
                  commentsBelow: "1/2/3"
            success : true
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /comments/create/:
    post:
      summary: Create Comment
      tags:
        - Comments
      parameters:
      
        - name: commentableType
          in: body
          schema:
           type: string
          description: |
            The options are "challenge", "comment", "conversations" and "idea".
          required : true
          
        - name: commentableId
          in: body
          schema:
           type: string
          description: "The _id of the document that is going to be commented"
          required: true
          
        - name: text
          in: body
          schema: 
            type: "string"
          description: "Text message"
          required: true  
        
        - name: files
          in: body
          schema:
            _id: "askjhqkwejasd"
            name: new_file.docx
            url: https://aws3.amazon.com/asldkjalsk123d.docx
          description: "The files that are going to be attached to the comment"
          required: false
          
      responses:
        200:
          description: The system verifies the session of the current user.
          schema:
            status  : 200
            message : "Successful Comment created"
            data    :
              _id   : "asdklajqwe123123"
              text : "Text message"
              
              files: 
                _id: "asdas123d123"
                name: "new_file.docx" 
                url: "https://aws3.amazon.com/asldkjalsk123d.docx"
              likeable: true
              likes : 0
              reported: false
              blocked: false
              createdBy: {}
              timestamps: 
                createdAt : "random date"
                updatedAt : "random date"
              commentsBelow: "0"
              
            success : true
            total   : 0
        401:
          description: The user doesn't have permissions to create
          schema:
            status  : 401
            message : "The user doesn't have permissions to create"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /comments/update/:
    post:
      summary: Update Comment
      parameters:
        
        - name: _id
          in: body
          schema: 
            type: string
          description: "The _id of the comment that is going to be update"
          required: true
        
        - name: files
          in: body
          schema:
           name: new_file.docx
           url: https://aws3.amazon.com/asldkjalsk123d.docx
          description: "The files that are going to be attached to the comment"
          required: false
          
        - name: text
          in: body
          schema: 
            type: "string"
          description: "New text message"
          required: false
          
      tags:
        - Comments
      responses:
        200:
          description: The system verifies the session of the current user. 
          schema:
            status  : 200
            message : "Successful Update Comment"
            data    :
              _id   : "asdklajqwe123123"
              text : "Text message"
              
              files: 
                _id: "asdas123d123"
                name: "new_file.docx" 
                url: "https://aws3.amazon.com/asldkjalsk123d.docx"
              likes : 0
              reported: false
              blocked: false
              createdBy: {}
              timestamps: 
                createdAt : "random date"
                updatedAt : "random date"
              commentsBelow: "0"
              
            success : true
            total   : 0
        401:
          description: The system can't find an active session
          schema:
            status  : 401
            message : "You do not have permissions"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /comments/like:
    post:
      summary: Like Comment
      parameters:
        - name: _id
          in: body
          schema:
           type: string
          description: "The _id of the comment that is going to recieve a like or is going to be unlike it"
          required: true
          
      tags:
        - Comment
      responses:
        200:
          description: The system verifies the session of the current user. 
          schema:
            status     : 200
            message    : "Like comment"
            data      :
              _id   : "asdklajqwe123123"
              text : "Some message"
              files: 
                _id: "12lasdlajakjsdhldjkasd"
                name: "new_file.docx"
                url: "https://aws3.amazon.com/asldkjalsk123d.docx"
              commentsBelow: "1/2/3"
              likeable: true/false
              likes: 2
              reported: false
              timestamps: 
                createdAt: "20-August-2014"
                updatedAt: "21-August-2014"
            success    : true
            total      : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /comments/index/reported:
    post:
      summary: Reported Comments
      parameters:
        - name: page
          in: body
          schema:
           type: string
          description: The count starts from 0.
          required: true
          
        - name: commentsPerPage
          in: body
          schema:
           type: string
          description: The comments that are going to be show per page
          required: true
          
      tags:
        - Comments
      responses:
        200:
          description: List comments
          schema:
            status  : 200
            message : "List comments"
            data      :
              objects : 
                - _id   : "asdklajqwe123123"
                  text : "Text message"
                  files: 
                    _id: "asdas123d123"
                    name: "new_file.docx" 
                    url: "https://aws3.amazon.com/asldkjalsk123d.docx"
                  likeable: true/false
                  editable : true/false
                  likes : 15
                  reported: true
                  blocked: false
                  createdBy: {}
                  reportedBy : {}
                  timestamps: 
                    createdAt : "random date"
                    updatedAt : "random date"
                  commentsBelow: "1/2/3"
            success : true
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            total   : 0
  
  /comments/report:
    post:
      summary: Report Comment
      parameters:
        - name: _id
          in: body
          schema:
           type: string
          description: The _id of the comment to be reported
          required: true
          
      tags:
        - Comments
      responses:
        200:
          description: The system verifies the session of the current user. 
          schema:
            status  : 200
            message : "Successful Update Comment"
            data    :
              _id   : "asdklajqwe123123"
              text : "Text message"
              
              files: 
                _id: "asdas123d123"
                name: "new_file.docx" 
                url: "https://aws3.amazon.com/asldkjalsk123d.docx"
              likes : 0
              reported: true
              blocked: false
              createdBy: {}
              timestamps: 
                createdAt : "random date"
                updatedAt : "random date"
              commentsBelow: "0"
              
            success : true
            total   : 0
        401:
          description: The system can't find an active session
          schema:
            status  : 401
            message : "You do not have permissions"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /comments/unreport:
    post:
      summary: Unreport Comment
      parameters:
        - name: _id
          in: body
          schema:
           type: string
          description: The _id of the comment to be unreported
          required: true
          
      tags:
        - Comments
      responses:
        200:
          description: The system verifies the session of the current user. 
          schema:
            status  : 200
            message : "Successful Update Comment"
            data    :
              _id   : "asdklajqwe123123"
              text : "Text message"
              
              files: 
                _id: "asdas123d123"
                name: "new_file.docx" 
                url: "https://aws3.amazon.com/asldkjalsk123d.docx"
              likes : 0
              reported: false
              blocked: false
              createdBy: {}
              timestamps: 
                createdAt : "random date"
                updatedAt : "random date"
              commentsBelow: "0"
              
            success : true
            total   : 0
        401:
          description: The system can't find an active session
          schema:
            status  : 401
            message : "You do not have permissions"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /comments/blocked:
    post:
      summary: Block a Comment
      
      parameters:
        - name: _id
          in: body
          schema:
           type: string
          description: The _id of the comment to be blocked
          required: true
          
      tags:
        - Comments
      responses:
        200:
          description: The system verifies the session of the current user. 
          schema:
            status  : 200
            message : "Successful Update Comment"
            data    :
              _id   : "asdklajqwe123123"
              text : "Text message"
              
              files: 
                _id: "asdas123d123"
                name: "new_file.docx" 
                url: "https://aws3.amazon.com/asldkjalsk123d.docx"
              likes : 0
              reported: true
              blocked: true
              createdBy: {}
              timestamps: 
                createdAt : "random date"
                updatedAt : "random date"
              commentsBelow: "0"
              
            success : true
            total   : 0
        401:
          description: The system can't find an active session
          schema:
            status  : 401
            message : "You do not have permissions"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
