swagger: '2.0'
info:
  title: Intrinno API
  description: Intrinno API
  version: "1.0.0"
  # the domain of the service
host: intrinno.mx:9000
  # array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /app/spec-files
produces:
  - application/json
paths:
  /configuration/saveConfigurations:
    post:
      summary: Save Terms and Privacy of Services (admin)
      description: |
        <b>Preconditions:</b> The user must be sign in into the server and must have an admin role.<br>
        <b>Postconditions:</b> There will be a new terms and privacy of services record into the database.
      parameters:
        - name: terms
          in: body
          schema:
           terms : 
            title: "Title 1"
            description: "Description 1"
            
          description : "This field contains an object that describes the terms"
          required : false
          
        - name : privacy
          in: body
          schema:
            privacy :
              title : "Title 2"
              description : "Description 2"
          description: "This field contains an object that describes the privacy"
          required: false
          
        - name : landing
          in: body
          schema:
            landing:
              title : "Intrinno"
              description : "For the company's sakes"
          description : |
            Here we put a brief description of the
            site and the title of the site.
          required : false
          
        - name : logo
          in: body
          schema:
            image:
              _id : "alsdjalskjdlaksd"
              name : "logo.png"
              base64: "asdkjalsdjqwne lqmlwe nlasndlas "
          description : |
            The object image that returns the call 
            "images/create"
          required: false
        
        - name : background
          in: body
          schema:
            image:
              _id : "alsdjalskjdlaksd"
              name : "background.png"
              base64: "kfgjlsnfd,zxc.zmx.,md.aqwe"
          description : |
            The object image that returns the call 
            "images/create"
          required: false
          
        - name : socialNetworks
          in: body
          schema:
            socialNetworks:
              facebook: "@facebook"
              twitter : "@twitter"
              email   : "contact@example.com"
          description : |
            The object that contains all socialNetworks.
          required: false
          
      tags:
        - Configurations
      responses:
        200:
          description: Create or Update Terms of services
          schema:
            status     : 200
            message    : "Create or Update Terms of services"
            data       : 
                _id   : "as123123ldkajsldkj1231231"
                terms :
                  title : "Title 1"
                  description: "Description 1"
                  
                privacy :
                  title : "Title 2"
                  description : "Description 2"
                
                landing:
                  title : "Intrinno"
                  description : "For the company's sakes"
                
                logo:  
                  _id : "alsdjalskjdlaksd"
                  name : "logo.png"
                  base64: "asdkjalsdjqwnelqmlwenlasndlas"
                  
                background:
                  _id : "alsdjalskjdlaksd"
                  name : "background.png"
                  base64: "kfgjlsnfd,zxc.zmx.,md.aqwe"
                  
                socialNetworks:
                  facebook: "@facebook"
                  twitter : "@twitter"
                  email   : "contact@example.com"
                  
                timestamps: 
                 createdAt: "20-August-2014"
                 updatedAt: "21-August-2014"
            success    : true
            total      : 0
        401:
          description: The system can't find an active session
          schema:
            status  : 401
            message : "You do not have permissions or Some is required"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
      
  /configuration/showConfigurations:
    post:
      summary: Show Terms and Privacy of Services (admin)
      description: |
        <b>Preconditions:</b> The user must be sign in into the server and must have an admin role.<br>
          
      tags:
        - Configurations
      responses:
        200:
          description: Create or Update Terms of services
          schema:
            status     : 200
            message    : "Show Terms of services"
            data       : 
                _id   : "as123123ldkajsldkj1231231"
                terms :
                  title : "Title 1"
                  description: "Description 1"
                  
                privacy :
                  title : "Title 2"
                  description : "Description 2"
                
                landing:
                  title : "Intrinno"
                  description : "For the company's sakes"
                
                logo:  
                  _id : "alsdjalskjdlaksd"
                  name : "logo.png"
                  base64: "asdkjalsdjqwnelqmlwenlasndlas"
                  
                background:
                  _id : "alsdjalskjdlaksd"
                  name : "background.png"
                  base64: "kfgjlsnfd,zxc.zmx.,md.aqwe"
                  
                socialNetworks:
                  facebook: "@facebook"
                  twitter : "@twitter"
                  email   : "contact@example.com"
                  
                timestamps: 
                 createdAt: "20-August-2014"
                 updatedAt: "21-August-2014"
            success    : true
            total      : 0
        401:
          description: The system can't find an active session
          schema:
            status  : 401
            message : "You do not have permissions or Some is required"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0

