swagger: '2.0'
info:
  title: Intrinno API
  description: Intrinno API
  version: "1.0.0"
  # the domain of the service
host: intrinno.mx:9000
  # array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /app/spec-files
produces:
  - application/json
paths:
  /images/create:
    post:
      summary: Upload Images
      description: |
        <b>Preconditions:</b> The user must be sign in into the server.<br>
        <b>Postconditions:</b> The system will create a new File document.
      parameters:
        - name: name
          in: body
          schema:
            type: string
          description: "Full name of the original image"
          required: true
        
        - name: base64
          in: body
          schema:
            type: string
          description: "Full string of the encrypted image"
          required: true  
          
      tags:
        - Images
      responses:
        200:
          description: Upload Image
          schema:
            status     : 200
            message    : "Succesful upload"
            data       : 
                _id   : "as123123ldkajsldkj1231231"
                name  : "original.png"
                base64: "asldkjasldkjalsnkdlansdasd"
                  
            success    : true
            total      : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
