swagger: '2.0'
info:
  title: Intrinno API
  description: |
    The value kind of every notification is a number from 0 to 11, that represents each of the following cases: <p>
    <ul>
    <li> <b>0</b>  : There is a new challenge where the consultant can participate. (notificationableType is challenge) </li>
    
    <li> <b>1</b>  : There is a new idea.  (notificationableType is "idea") </li>
    
    <li> <b>2</b>  : The user was chosen as a finalist of a challenge. (notificationableType is "challenge") </li>
    
    <li> <b>3</b>  : The user was chosen as a winner of a challenge. (notificationableType is "challenge") </li>
    
    <li> <b>4</b>  : A conversation was created where the user can comment. (notificationableType is "conversation") </li>
    
    <li> <b>5</b> : A comment was created for a message where the user is participant. 
                    (notificationableType is "conversation")</li>
    
    <li> <b>6</b>  : Some user commented on a challenge where the user is participant or owner. 
                    (notificationableType is "challenge") </li>
                    
    <li> <b>7</b>  : Some user reported a comment. (there is no notificationableType and notificationableId)</li>
    
    <li> <b>8</b>  : Some user click on the like button of an idea that the user posted. 
                    (notificationableType is "idea") </li>
                    
    <li> <b>9</b>  : Some user click on the like button of a comment (or a comment of a comment) that the user posted in a challenge. 
                    (notificationableType is "challenge") </li>
                    
    <li> <b>10</b>  : Some user click on the like button of a comment (or a comment of a comment)
    that the user posted in a idea. 
                    (notificationableType is "idea") </li>
                    
    <li> <b>11</b>  : Some consultant reclaim one reward and the notification is created for the admin.
                    (notificationableType is "rewardsUsers") </li>
                    
    <li> <b>12</b>  : Some user commented on an idea where the user is participant or owner. 
                    (notificationableType is "idea") (NO IMPLEMENTED YET)</li>
    
    </ul>
    
    <b>NOTE</b> : Every notification has two users, "user" and "createdBy", the field user indicates who is the owner to 
    the notification and the field createdBy indicates who did the action that throws the notification. <p>
    There exists two channels, "messages" and "notifications"
    
    
  version: "1.0.0"
  # the domain of the service
host: intrinno.mx:9000
  # array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /app/spec-files
produces:
  - application/json
paths:
  /notifications/index:
    post:
      summary: List Notifications
      tags:
        - Notifications
      parameters:
      
        - name: page
          in: body
          schema:
           type: integer
          description: The count starts from 0.
          required : true
          
        - name: notificationsPerPage
          in: body
          schema: 
           type: integer
          description: "The notifications that are going to be show per page"
          required: true
          
      responses:
        200:
          description: List notifications
          schema:
            status  : 200
            message : "List notifications"
            data      :
              unRead : 15
              objects : 
                - _id   : "asdklajqwe123123"
                  notificationableType : "challenge"
                  notificationableId   : "alskdk1n2k3sadmnqwe"
                  read : false
                  blocked : false
                  kind    : 0
                  user  :
                    firstName : "User"
                    lastName  : "Example"
                    avatar    : {}
                  createdBy:
                    firstName : "User 2"
                    lastName : "Example 2"
                    avatar : {}
                  timestamps: 
                    createdAt : "random date"
                    updatedAt : "random date"
                    
                - _id   : "asldjl1n2l3j"
                  notificationableType : "idea"
                  notificationableId   : "asl123asdmn12i3"
                  read : true
                  blocked : false
                  kind    : 2
                  user  :
                    firstName : "User"
                    lastName  : "Example"
                    avatar    : {}
                  createdBy:
                    firstName : "User 2"
                    lastName : "Example 2"
                    avatar : {}
                  timestamps: 
                    createdAt : "random date"
                    updatedAt : "random date"
            success : true
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /notifications/read:
    post:
      summary: Update notification
      tags:
        - Notifications
      parameters:
      
        - name: _id
          in: body
          schema:
           type: string
          description: The _id of the notification
          required : true
          
      responses:
        200:
          description: Update notifications
          schema:
            status  : 200
            message : "Notification updated"
            data      :
              _id   : "asldjl1n2l3j"
              notificationableType : "idea"
              notificationableId   : "asl123asdmn12i3"
              read : true
              blocked : false
              kind    : 2
              user  :
                firstName : "User"
                lastName  : "Example"
                avatar    : {}
              createdBy:
                firstName : "User 2"
                lastName : "Example 2"
                avatar : {}
              timestamps: 
                createdAt : "random date"
                updatedAt : "random date"
            success : true
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0

  /notifications/reset:
    post:
      summary: Update notifications count to zero
      tags:
        - Notifications
          
      responses:
        200:
          description: Count reseted
          schema:
            status  : 200
            message : "Count reseted"
            data    : {}
            success : true
            total   : 0

 
            
            

  /messages/index:
    post:
      summary: List Messages
      tags:
        - Messages
      parameters:
      
        - name: page
          in: body
          schema:
           type: integer
          description: The count starts from 0.
          required : true
          
        - name: messagesPerPage
          in: body
          schema: 
           type: integer
          description: "The messages that are going to be show per page"
          required: true
          
        - name: filter
          in: body
          schema:
           filter: 
            read: "true/false"
          description: "Filters to be apply"
          required: false
          
      responses:
        200:
          description: List messages
          schema:
            status  : 200
            message : "List messages"
            data      :
              unRead : 15
              objects : 
                - _id   : "asdklajqwe123123"
                  notificationableType : "conversation"
                  notificationableId   : "alskdk1n2k3sadmnqwe"
                  read : false
                  blocked : false
                  kind    : 0
                  user  :
                    firstName : "User"
                    lastName  : "Example"
                    avatar    : {}
                  createdBy:
                    firstName : "User 2"
                    lastName : "Example 2"
                    avatar : {}
                  timestamps: 
                    createdAt : "random date"
                    updatedAt : "random date"
                    
                - _id   : "asldjl1n2l3j"
                  notificationableType : "conversation"
                  notificationableId   : "asl123asdmn12i3"
                  read : true
                  blocked : false
                  kind    : 2
                  user  :
                    firstName : "User"
                    lastName  : "Example"
                    avatar    : {}
                  createdBy:
                    firstName : "User 2"
                    lastName : "Example 2"
                    avatar : {}
                  timestamps: 
                    createdAt : "random date"
                    updatedAt : "random date"
            success : true
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /messages/read:
    post:
      summary: Update message
      tags:
        - Messages
      parameters:
      
        - name: _id
          in: body
          schema:
           type: string
          description: The _id of the message
          required : true
          
      responses:
        200:
          description: Update messages
          schema:
            status  : 200
            message : "Message updated"
            data      :
              _id   : "asldjl1n2l3j"
              notificationableType : "conversation"
              notificationableId   : "asl123asdmn12i3"
              read : true
              blocked : false
              kind    : 2
              user  :
                firstName : "User"
                lastName  : "Example"
                avatar    : {}
              createdBy:
                    firstName : "User 2"
                    lastName : "Example 2"
                    avatar : {}
              timestamps: 
                createdAt : "random date"
                updatedAt : "random date"
            success : true
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
 
  /messages/reset:
    post:
      summary: Update messages count to zero
      tags:
        - Messages
          
      responses:
        200:
          description: Count reseted
          schema:
            status  : 200
            message : "Count reseted"
            data    : {}
            success : true
            total   : 0

 
