swagger: '2.0'
info:
  title: Intrinno API
  description: Intrinno API
  version: "1.0.0"
  # the domain of the service
host: intrinno.mx:9000
  # array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /app/spec-files
produces:
  - application/json
paths:
  /proposals/index/:
    post:
      summary: List proposals (paginate)
      tags:
        - Proposals
      parameters:
        - name: page
          in: body
          schema:
           type: integer
           minimum : 0
          description: "The count start from 0"
          required : true
          
        - name: proposalsPerPage
          in: body
          schema: 
           type: integer
           minimum: 1
           maximum: 50
          description: "We only list 1-50 elements, no less no more"
          required: true
          
        - name: filter
          in: body
          schema:
            challengeId : "lkasdlkj123k90098098"
            userId      : "asd129askjclñkoihew"
            delivered   : "true/false"
            owner       : "true/false"
            admin       : "true/false"
          description: |
            All the fields of filter are optionals. 
            The flag admin indicates if the
            request is used for an admin user
          required: false
          
      responses:
        200:
          description: List proposals
          schema:
            status  : 200
            message : "List proposals"
            data      :
              objects : 
                _id   : "asdklajqwe123123"
                challenge : "asdlkj12nlvcxlñ9032"
                user      : "asdlk1290231ñlkdaskj"
                title       : "Some random title"
                winner      : "true/false"
                delivered   : "true/false"
                files: 
                  id  : "asdasd"
                  name: "new_file.docx"
                  url : "https://aws3.amazon.com/asldkjalskd.png"
                  createdBy: {}
                timestamps: 
                  createdAt: "20-August-2014"
                  updatedAt: "21-August-2014"
            success : true
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /proposals/show/:
    post:
      summary: Show proposal
      description: |
        <b>Preconditions:</b> The user must be sign in into the server and must have an admin role or be the owner of the proposal.
      parameters:
        - name: _id
          in: body
          schema:
           type: string
          description: "as123123ldkajsldkj1231231"
      tags:
        - Proposals
      responses:
        200:
          description: The system verifies the session of the current user. 
          schema:
            status     : 200
            message    : "Show Proposal"
            data      :
              _id   : "asdklajqwe123123"
              challengeId : "asdlkj12nlvcxlñ9032"
              userId  : "asdlk1290231ñlkdaskj"
              title: "Some random title"
              description: "Some random description"
              winner: true/false
              delivered: true/false
              cost: "1/2/3.."
              patent: true/false
              outsourcing: true/false
              experience: "Description of his curriculum"
              businessName: true(persona moral)/false(persona fisica)
              duration: "Text that describe the duration of the project"
              type: "prototype/operative/license"
              company:
                name: "Umbrella"
                foreigner: true/false
              files: 
                id  : "asdasd"
                name: "new_file.docx"
                url : "https://aws3.amazon.com/asldkjalskd.png"
              timestamps: 
                createdAt: "20-August-2014"
                updatedAt: "21-August-2014"
              createdBy : {} 
            success    : true
            total      : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            

  /proposals/create/:
    post:
      summary: Create Proposal (consultant)
      tags:
        - Proposals
      parameters:
        - name: challenge
          in: body
          schema:
            _id   : "asdklajqwe123123"
            title : "title"
            description : "Some random description"
            startDate  : "Mon Nov 24 2014 22:15:07 GMT-0600 (CST)"
            endDate    : "Wed Nov 30 2014 16:20:50 GMT-0600 (CST)"
            status     : "open/close/created/finalists/winner/noWinner/ended"
            accessibility: "public/private"
            blocked : false/true
            specifications : "Description of all the points that the proposal must have"
            objective : "The objective of this challenge"


            avatar:
              _id  : "lvÃƒÂ±jasu230vnl"
              name: "new_avatar.png"
              url : "https://aws3.amazon.com/asldkjalskd.png"

            background:
              _id  : "dsjkbk1op12d01dfasdad"
              name: "new_background.png"
              url : "https://aws3.amazon.com/asldkjalskd.png"

            rewards :
              - title: "Pack of books"
                description: "Contains a collection..."
                place: 1
                points : 200
                photos:
                  - _id: "aqwlknsxczklnc"
                    name: "photo1.png"
                    url: "https://aws3.amazon.com/asldkjalsk123123d.png"
            
            createdBy :
              _id : "asdlkjaÃƒÂ±sjdÃƒÂ±123"
              avatar :
                _id: "12i3ojsaldkjaslkd"
                name : "avatar.jpg"
                url : "https://aws3.amazon.com/asldkjalsk123123d123123.png"
              firstName: "Leon"
              lastName: "S. Kennedy"
              email : "user@example.com"

            groups:
              - _id: "as123123ldkajs"
                name: "Grupo 1"
              - _id: "aslihdqlkwjel12j3"
                name: "Grupo 2"

            categories:
              - _id: "as123123ldkajsldkj1231343"
                name : "Social Media"
              - _id : "asda10knffkjb"
                name : "Development"

            priorities:
              - _id: "733hfsdfh3347sfjsdf"
                name: "cost"
                range: [100,200]
                priority: 1

              - _id : "asldhql3jlkjasd123"
                name : "duration"
                range: [50,100]
                priority : 2

              - _id : "12oi3upkfba"
                name : "experienceTime"
                range: [1,3]
                priority : 3

              - _id : "12o3u12pou3ad123"
                name : "patent"
                range : [true/false]
                priority : 4

              - _id : "123hlaksdlkasd"
                name : "outsourcing"
                range : [true/false]
                priority : 5

              - _id : "123iulaksdlakjsdrqwe"
                name : "businessName"
                range : [true/false]
                priority : 1

              - _id: "asp12oi3oi123dfsdf"
                name : "foreigner"
                range : [true/false]
                priority : 2

              - _id : "asdh3po24jnsfaa"
                name : "kind"
                range : ["empty", "patent", "secret", "industry", "prototype"]
                priority : 3

              - _id : "aslkd1p23udf"
                name : "country"
                range : ["Mexico", "EU", "Canada"]
                priority : 4

              - _id : "asdp9i243jkbs"
                name : "state"
                range : ["California", "Yucatan", "Oregon"]
                priority : 5

            files:
              - _id : "sddfl21kj3kjhasd"
                name: "new_file.docx"
                url : "https://aws3.amazon.com/asldkjalskd.png"

            timestamps:
              createdAt: "20-August-2014"
              updatedAt: "20-August-2014"
          description: |
            The challenge document that is return from 
            challenge/show
          required : true
          
        - name: title
          in: body
          schema: 
           type: string
          description: "Title"
          required: true
          
        - name: description
          in: body
          schema: 
           type: string
          description: "Some random description"
          required : true
          
        - name: delivered
          in: body
          schema: 
           type: boolean
          description: |
            True when the user wants to send his proposal
            to the admin. The default value is false.
          required: false
          
        - name : kind
          in: body
          schema:
            type : string
          description: |
            The options are "empty", "patent", "secret",
            "industry" and "prototype"
          required: false
          
        - name: company
          in: body
          schema: 
            name : "The name of the company"
            foreigner: true/false
          
          description: |
            A document with basic information of the 
            company who propose.
            
          required: false
          
        - name : cost
          in: body
          schema : 
            type: integer
          description : |
            A number more than 1 that express the 
            total cost of the proposal.
          required : false
          
        - name: patent
          in: body
          schema: 
           type: boolean
          description: "True or false"
          required: false
          
        - name: outsourcing
          in: body
          schema: 
           type: string
          description: "true/false"
        - name: experience
          in: body
          schema: 
           type: string
          description: "Description of his curriculum"
        - name: businessName
          in: body
          schema: 
           type: string
          description: "true(persona moral)/false(persona fisica)"
        - name: duration
          in: body
          schema: 
           type: string
          description: "Text that describe the duration of the project"
        - name: type
          in: body
          schema: 
           type: string
          description: "prototype/operative/license"

        - name: files
          in: body
          schema: 
            id  : "asdasd"
            name: "new_file.docx"
            url : "https://aws3.amazon.com/asldkjalskd.png"
            createdBy: {}
          description: "[{'_id': 'asdas123d123', 'name': 'new_file.docx', 'url': 'https://aws3.amazon.com/asldkjalsk123d.docx'}...]"
      responses:
        200:
          description: The system verifies the session of the current user.
          schema:
            status  : 200
            message : "Successful create participant"
            data    :
              _id   : "asdklajqwe123123"
              challengeId : "asdlkj12nlvcxlñ9032"
              userId  : "asdlk1290231ñlkdaskj"
              title: "Some random title"
              description: "Some random description"
              winner: true/false
              delivered: true/false
              cost: "1/2/3.."
              patent: true/false
              outsourcing: true/false
              experience: "Description of his curriculum"
              businessName: true(persona moral)/false(persona fisica)
              duration: "Text that describe the duration of the project"
              type: "prototype/operative/license"
              company:
                name: "Umbrella"
                foreigner: true/false
              files: 
                id  : "asdasd"
                name: "new_file.docx"
                url : "https://aws3.amazon.com/asldkjalskd.png"
              timestamps: 
                createdAt: "20-August-2014"
                updatedAt: "21-August-2014"
              createdBy : {} 
            success : true
            total   : 0
        401:
          description: The user doesn't have permissions to create a user or Some is required or The challenge doesn't exists or You already create a proposal.
          schema:
            status  : 401
            message : "The user doesn't have permissions to create a user or Some is required or The challenge doesn't exists or You already create a proposal"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /proposals/update/:
    post:
      summary: Update Proposal Information (consultant)
      description: |
        <b>Preconditions:</b> The user must be sign in into the server and must have an consultant role.<br>
        <b>Postconditions:</b> The information will be update.
      parameters:
        - name: challengeId
          in: body
          schema:
           type: string
          description: "asdlkj12nlvcxlñ9032"
        - name: title
          in: body
          schema: 
           type: string
          description: "Some random title"
        - name: description
          in: body
          schema: 
           type: string
          description: "Some random description"
        - name: delivered
          in: body
          schema: 
           type: string
          description: "true/false"
        - name: cost
          in: body
          schema: 
           type: string
          description: "1/2/3"
        - name: patent
          in: body
          schema: 
           type: string
          description: "true/false"
        - name: outsourcing
          in: body
          schema: 
           type: string
          description: "true/false"
        - name: experience
          in: body
          schema: 
           type: string
          description: "Description of his curriculum"
        - name: businessName
          in: body
          schema: 
           type: string
          description: "true(persona moral)/false(persona fisica)"
        - name: duration
          in: body
          schema: 
           type: string
          description: "Text that describe the duration of the project"
        - name: type
          in: body
          schema: 
           type: string
          description: "prototype/operative/license"
        - name: company
          in: body
          schema: 
           name: Umbrella
           foreigner: true/false
          description: "{'name': 'Umbrella', 'foreigner': 'true/false'}"
        - name: files
          in: body
          schema: 
            id  : "asdasd"
            name: "new_file.docx"
            url : "https://aws3.amazon.com/asldkjalskd.png"
            createdBy: {}
          description: "[{'_id': 'asdas123d123', 'name': 'new_file.docx', 'url': 'https://aws3.amazon.com/asldkjalsk123d.docx'}...]"
      tags:
        - Proposals
      responses:
        200:
          description: The system verifies the session of the current user. 
          schema:
            status  : 200
            message : "Successful Update Proposal"
            data    :
              _id   : "asdklajqwe123123"
              challengeId : "asdlkj12nlvcxlñ9032"
              userId  : "asdlk1290231ñlkdaskj"
              title: "Some random title"
              description: "Some random description"
              winner: true/false
              delivered: true/false
              cost: "1/2/3.."
              patent: true/false
              outsourcing: true/false
              experience: "Description of his curriculum"
              businessName: true(persona moral)/false(persona fisica)
              duration: "Text that describe the duration of the project"
              type: "prototype/operative/license"
              company:
                name: "Umbrella"
                foreigner: true/false
              files: 
                id  : "asdasd"
                name: "new_file.docx"
                url : "https://aws3.amazon.com/asldkjalskd.png"
              timestamps: 
                createdAt: "20-August-2014"
                updatedAt: "21-August-2014"
              createdBy : {} 
            success : true
            total   : 0
        401:
          description: The system can't find an active session
          schema:
            status  : 401
            message : "You do not have permissions"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /proposals/delete/:
    post:
      summary: Delete Proposal (owner)
      parameters:
        - name: _id
          in: body
          schema:
           type: string
          description: asdasd21323123asd  
      tags:
        - Proposals
      responses:
        200:
          description: Succesfull delete Proposal
          schema:
            status     : 200
            message    : "Succesfull delete Proposal"
            data      :
              _id   : "asdklajqwe123123"
              challengeId : "asdlkj12nlvcxlñ9032"
              userId  : "asdlk1290231ñlkdaskj"
              title: "Some random title"
              description: "Some random description"
              winner: true/false
              delivered: true/false
              cost: "1/2/3.."
              patent: true/false
              outsourcing: true/false
              experience: "Description of his curriculum"
              businessName: true(persona moral)/false(persona fisica)
              duration: "Text that describe the duration of the project"
              type: "prototype/operative/license"
              company:
                name: "Umbrella"
                foreigner: true/false
              files: 
                id  : "asdasd"
                name: "new_file.docx"
                url : "https://aws3.amazon.com/asldkjalskd.png"
              timestamps: 
                createdAt: "20-August-2014"
                updatedAt: "21-August-2014"
              createdBy : {} 
            success    : true
            total      : 0
        401:
          description: The user doesn't have permissions or record not found.
          schema:
            status  : 401
            message : "The user doesn't have permissions or record not found"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
