swagger: '2.0'
info:
  title: Intrinno API
  description: Intrinno API
  version: "1.0.0"
  # the domain of the service
host: intrinno.mx:9000
  # array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /app/spec-files
produces:
  - application/json
paths:
  /proposals/index/:
    post:
      summary: List proposals (paginate)
      tags:
        - Proposals
      parameters:
        - name: page
          in: body
          schema:
           type: integer
          description: "1"
        - name: proposalsPerPage
          in: body
          schema: 
           type: integer
          description: "20"
        - name: filter
          in: body
          schema:
            challengeId        : "lkasdlkj123k90098098c098"
            userId       : "asd129askjclñkoihew"
            winner : "true/false"
            delivered   : "true/false"
            owner: "true/false"
          description: "'filter': {'challengeId': 'lkasdlkj123k90098098c098', 'userId': 'asd129askjclñkoihew', 'winner': true/false, 'delivered': true/false, 'owner': true/false}"
          required: true
      responses:
        200:
          description: List proposals
          schema:
            status  : 200
            message : "List proposals"
            data      :
              objects : 
                _id   : "asdklajqwe123123"
                challengeId : "asdlkj12nlvcxlñ9032"
                userId      : "asdlk1290231ñlkdaskj"
                title       : "Some random title"
                winner      : "true/false"
                delivered   : "true/false"
                files: 
                  id  : "asdasd"
                  name: "new_file.docx"
                  url : "https://aws3.amazon.com/asldkjalskd.png"
                  createdBy: {}
                timestamps: 
                  createdAt: "20-August-2014"
                  updatedAt: "21-August-2014"
            success : true
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /proposals/create/:
    post:
      summary: Create Proposal (consultant)
      tags:
        - Proposals
      parameters:
        - name: challengeId
          in: body
          schema:
           type: string
          description: "asdlkj12nlvcxlñ9032"
        - name: title
          in: body
          schema: 
           type: string
          description: "Some random title"
        - name: description
          in: body
          schema: 
           type: string
          description: "Some random description"
        - name: delivered
          in: body
          schema: 
           type: string
          description: "true/false"
        - name: cost
          in: body
          schema: 
           type: string
          description: "1/2/3"
        - name: patent
          in: body
          schema: 
           type: string
          description: "true/false"
        - name: outsourcing
          in: body
          schema: 
           type: string
          description: "true/false"
        - name: experience
          in: body
          schema: 
           type: string
          description: "Description of his curriculum"
        - name: businessName
          in: body
          schema: 
           type: string
          description: "true(persona moral)/false(persona fisica)"
        - name: duration
          in: body
          schema: 
           type: string
          description: "Text that describe the duration of the project"
        - name: type
          in: body
          schema: 
           type: string
          description: "prototype/operative/license"
        - name: company
          in: body
          schema: 
           name: Umbrella
           foreigner: true/false
          description: "{'name': 'Umbrella', 'foreigner': 'true/false'}"
        - name: files
          in: body
          schema: 
            id  : "asdasd"
            name: "new_file.docx"
            url : "https://aws3.amazon.com/asldkjalskd.png"
            createdBy: {}
          description: "[{'_id': 'asdas123d123', 'name': 'new_file.docx', 'url': 'https://aws3.amazon.com/asldkjalsk123d.docx'}...]"
      responses:
        200:
          description: The system verifies the session of the current user.
          schema:
            status  : 200
            message : "Successful create participant"
            data    :
              _id   : "asdklajqwe123123"
              challengeId : "asdlkj12nlvcxlñ9032"
              userId  : "asdlk1290231ñlkdaskj"
              title: "Some random title"
              description: "Some random description"
              winner: true/false
              delivered: true/false
              cost: "1/2/3.."
              patent: true/false
              outsourcing: true/false
              experience: "Description of his curriculum"
              businessName: true(persona moral)/false(persona fisica)
              duration: "Text that describe the duration of the project"
              type: "prototype/operative/license"
              company:
                name: "Umbrella"
                foreigner: true/false
              files: 
                id  : "asdasd"
                name: "new_file.docx"
                url : "https://aws3.amazon.com/asldkjalskd.png"
              timestamps: 
                createdAt: "20-August-2014"
                updatedAt: "21-August-2014"
              createdBy : {} 
            success : true
            total   : 0
        401:
          description: The user doesn't have permissions to create a user or Some is required or The challenge doesn't exists or You already create a proposal.
          schema:
            status  : 401
            message : "The user doesn't have permissions to create a user or Some is required or The challenge doesn't exists or You already create a proposal"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /proposals/update/:
    post:
      summary: Update Proposal Information (consultant)
      description: |
        <b>Preconditions:</b> The user must be sign in into the server and must have an consultant role.<br>
        <b>Postconditions:</b> The information will be update.
      parameters:
        - name: challengeId
          in: body
          schema:
           type: string
          description: "asdlkj12nlvcxlñ9032"
        - name: title
          in: body
          schema: 
           type: string
          description: "Some random title"
        - name: description
          in: body
          schema: 
           type: string
          description: "Some random description"
        - name: delivered
          in: body
          schema: 
           type: string
          description: "true/false"
        - name: cost
          in: body
          schema: 
           type: string
          description: "1/2/3"
        - name: patent
          in: body
          schema: 
           type: string
          description: "true/false"
        - name: outsourcing
          in: body
          schema: 
           type: string
          description: "true/false"
        - name: experience
          in: body
          schema: 
           type: string
          description: "Description of his curriculum"
        - name: businessName
          in: body
          schema: 
           type: string
          description: "true(persona moral)/false(persona fisica)"
        - name: duration
          in: body
          schema: 
           type: string
          description: "Text that describe the duration of the project"
        - name: type
          in: body
          schema: 
           type: string
          description: "prototype/operative/license"
        - name: company
          in: body
          schema: 
           name: Umbrella
           foreigner: true/false
          description: "{'name': 'Umbrella', 'foreigner': 'true/false'}"
        - name: files
          in: body
          schema: 
            id  : "asdasd"
            name: "new_file.docx"
            url : "https://aws3.amazon.com/asldkjalskd.png"
            createdBy: {}
          description: "[{'_id': 'asdas123d123', 'name': 'new_file.docx', 'url': 'https://aws3.amazon.com/asldkjalsk123d.docx'}...]"
      tags:
        - Proposals
      responses:
        200:
          description: The system verifies the session of the current user. 
          schema:
            status  : 200
            message : "Successful Update Proposal"
            data    :
              _id   : "asdklajqwe123123"
              challengeId : "asdlkj12nlvcxlñ9032"
              userId  : "asdlk1290231ñlkdaskj"
              title: "Some random title"
              description: "Some random description"
              winner: true/false
              delivered: true/false
              cost: "1/2/3.."
              patent: true/false
              outsourcing: true/false
              experience: "Description of his curriculum"
              businessName: true(persona moral)/false(persona fisica)
              duration: "Text that describe the duration of the project"
              type: "prototype/operative/license"
              company:
                name: "Umbrella"
                foreigner: true/false
              files: 
                id  : "asdasd"
                name: "new_file.docx"
                url : "https://aws3.amazon.com/asldkjalskd.png"
              timestamps: 
                createdAt: "20-August-2014"
                updatedAt: "21-August-2014"
              createdBy : {} 
            success : true
            total   : 0
        401:
          description: The system can't find an active session
          schema:
            status  : 401
            message : "You do not have permissions"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /proposals/show/:
    post:
      summary: Show proposal
      description: |
        <b>Preconditions:</b> The user must be sign in into the server and must have an admin role or be the owner of the proposal.
      parameters:
        - name: _id
          in: body
          schema:
           type: string
          description: "as123123ldkajsldkj1231231"
      tags:
        - Proposals
      responses:
        200:
          description: The system verifies the session of the current user. 
          schema:
            status     : 200
            message    : "Show Proposal"
            data      :
              _id   : "asdklajqwe123123"
              challengeId : "asdlkj12nlvcxlñ9032"
              userId  : "asdlk1290231ñlkdaskj"
              title: "Some random title"
              description: "Some random description"
              winner: true/false
              delivered: true/false
              cost: "1/2/3.."
              patent: true/false
              outsourcing: true/false
              experience: "Description of his curriculum"
              businessName: true(persona moral)/false(persona fisica)
              duration: "Text that describe the duration of the project"
              type: "prototype/operative/license"
              company:
                name: "Umbrella"
                foreigner: true/false
              files: 
                id  : "asdasd"
                name: "new_file.docx"
                url : "https://aws3.amazon.com/asldkjalskd.png"
              timestamps: 
                createdAt: "20-August-2014"
                updatedAt: "21-August-2014"
              createdBy : {} 
            success    : true
            total      : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
            
  /proposals/delete/:
    post:
      summary: Delete Proposal (owner)
      parameters:
        - name: _id
          in: body
          schema:
           type: string
          description: asdasd21323123asd  
      tags:
        - Proposals
      responses:
        200:
          description: Succesfull delete Proposal
          schema:
            status     : 200
            message    : "Succesfull delete Proposal"
            data      :
              _id   : "asdklajqwe123123"
              challengeId : "asdlkj12nlvcxlñ9032"
              userId  : "asdlk1290231ñlkdaskj"
              title: "Some random title"
              description: "Some random description"
              winner: true/false
              delivered: true/false
              cost: "1/2/3.."
              patent: true/false
              outsourcing: true/false
              experience: "Description of his curriculum"
              businessName: true(persona moral)/false(persona fisica)
              duration: "Text that describe the duration of the project"
              type: "prototype/operative/license"
              company:
                name: "Umbrella"
                foreigner: true/false
              files: 
                id  : "asdasd"
                name: "new_file.docx"
                url : "https://aws3.amazon.com/asldkjalskd.png"
              timestamps: 
                createdAt: "20-August-2014"
                updatedAt: "21-August-2014"
              createdBy : {} 
            success    : true
            total      : 0
        401:
          description: The user doesn't have permissions or record not found.
          schema:
            status  : 401
            message : "The user doesn't have permissions or record not found"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0