swagger: '2.0'
info:
  title: Intrinno API
  description: Intrinno API
  version: "1.0.0"
  # the domain of the service
host: intrinno.mx:9000
  # array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /app/spec-files
produces:
  - application/json
paths:
  /forgot_password:
    post:
      summary: Sessions Forgot  Password
      description: |
        <b>Preconditions:</b> The email must be registered into the system. <br>
        <b>Postconditions:</b> The system will send an email to reset password.
      tags:
        - Sessions
      parameters:
        - name: email
          in: body
          schema:
           type: string
          description: user@example.com
          required: true
      responses:
        200:
          description: Password reset
          schema:
            status  : 200
            message : "Password Reset"
            data    :
              email : "user@example.com"
            success : true
            total   : 0
        
        401:
          description: Email is not registered or the user is not activated
          schema:
            status  : 401
            message : "Email is not registered/The user is not activated"
            data    : {}
            success : false
            total   : 0
        500:
          description: Some internal error occurs
          schema:
            status  : 500
            message : "Some internal error ocurrs"
            data    : {}
            success : false
            total   : 0
 
